#!/bin/bash
#Script to sort BUSCO output into gene folders for phylogenomics

display_usage() {
	echo ""
	echo "USAGE: $0 [OPTIONS]"
    echo ""
	echo "OPTIONS"
    echo "  -d, --directory"
    echo "      Directory containing busco output folders which must have the typical 'run_' prefix"
    echo ""
    echo "EXAMPLE"
	echo "  $0 -d /data/busco_folders"
    echo ""
    exit
}

if [ -z "$1" ]
then
    display_usage
    exit
fi

while [ "$#" -gt 0 ]
do
    ARGUMENTS="$1"
    case $ARGUMENTS in
        -h|--help)
        display_usage
        ;;
        -d|--directory)
        DIRECTORY="$2"
        shift
    esac
    shift
done

if [ -z "$DIRECTORY" ]
then
    echo ""
    echo "Missing required options"
    display_usage
    echo ""
    echo "Exiting..."
    exit
fi

echo "`date -u`"
echo "-------------------------------------------------"
echo "Starting $0"
echo "-------------------------------------------------"

ls -d ${DIRECTORY}/run_* | sed s/^.*\\/\// | cut -f 2- -d '_' > ${DIRECTORY}/assembly_list

echo "List of all assemblies in the provided directory written to ${DIRECTORY}/assembly_list"

LIST=${DIRECTORY}/assembly_list

#Make text file with BUSCO stats

for assembly in `cat $LIST`
do
    grep "C:" ${DIRECTORY}/run_${assembly}/short_summary_* >> tmp
done

paste $LIST tmp > ${DIRECTORY}/busco_stats

rm tmp

echo "Summary of BUSCO statistics written to ${DIRECTORY}/busco_stats.txt"

#Filter for common BUSCOs

dirs=(`ls -d ${DIRECTORY}/*/single_copy_busco_sequences`)

find "${dirs[@]}" -maxdepth 1 -type f -name "*.fna" -printf '%f\n' | sort | uniq -c | sed -n "s/^ *${#dirs[@]} //p" > ${DIRECTORY}/busco_list

echo "List of `cat ${DIRECTORY}/busco_list | wc -l` common single copy BUSCOs from all assemblies written to ${DIRECTORY}/busco_list"

#Copy and rename only common BUSCOs

n=0

for assembly in `cat $LIST`
do
    mkdir ${DIRECTORY}/run_${assembly}/for_phylo

    for busco in `cat ${DIRECTORY}/busco_list | cut -f 1 -d '.'`
    do
        cp ${DIRECTORY}/run_${assembly}/single_copy_busco_sequences/${busco}.fna ${DIRECTORY}/run_${assembly}/for_phylo/${busco}_${assembly}
        
        #Replace fasta header with assembly name
        sed -i "1s/.*/>${assembly}/" ${DIRECTORY}/run_${assembly}/for_phylo/${busco}_${assembly}
    done
    
    n=$((n+1))
    echo "Extracting common BUSCOs, assembly ${n} / `cat $LIST | wc -l`"
done

#Move into new folder of fasta files

n=0

mkdir ${DIRECTORY}/fasta

for busco in `cat ${DIRECTORY}/busco_list | cut -f 1 -d '.'`
do
    cat ${DIRECTORY}/*/for_phylo/${busco}* > ${DIRECTORY}/fasta/${busco}.fa
    
    n=$((n+1))
    echo "Writing fasta file for BUSCO ${n} / `cat ${DIRECTORY}/busco_list | wc -l`"
done

#Check number of sequences in fasta files

for busco in `cat ${DIRECTORY}/busco_list | cut -f 1 -d '.'`
do
    fgrep -o '>' ${DIRECTORY}/fasta/${busco}.fa | wc -l > tmp

    if [ `cat tmp` != `cat ${LIST} | wc -l` ]
    then
        echo ${busco} >> ${DIRECTORY}/fasta/error_list
    fi
    
done

echo "Fasta files ready to align in ${DIRECTORY}/fasta"

if [ -f ${DIRECTORY}/fasta/error_list ]
then
    echo "`cat ${DIRECTORY}/fasta/error_list | wc -l` fasta files have the wrong number of taxa. BUSCO IDs have been printed to ${DIRECTORY}/fasta/error_list, please check these files manually before trying to align"
fi

rm tmp
rm -r ${DIRECTORY}/*/for_phylo

echo "-------------------------------------------------"
echo "Finished `date -u`"
echo "-------------------------------------------------"